---

- name: systemctl daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_facts.service_mgr | lower == "systemd"

- name: reload powerdns-recursor
  become: true
  ansible.builtin.service:
    name: "{{ pdns_recursor_service.name }}"
    state: reloaded
  when:
    - not running_in_check_mode

- name: restart powerdns-recursor
  become: true
  ansible.builtin.service:
    name: "{{ pdns_recursor_service.name }}"
    state: restarted
  when:
    - not running_in_check_mode

...
